[python with prybar] update pkg building stderred
Why
===
* We were getting:

```
building '/nix/store/hmfp9y0w181bywzy02b9pyvbd5ai0p6s-stderred-0.1.0-vendor.tar.gz.drv'...29:41
error: builder for '/nix/store/hmfp9y0w181bywzy02b9pyvbd5ai0p6s-stderred-0.1.0-vendor.tar.gz.drv' failed with exit code 101;29:41
       last 10 log lines:29:41
       > error: failed to sync29:41
       >29:41
       > Caused by:29:41
       >   failed to load pkg lockfile29:41
       >29:41
       > Caused by:29:41
       >   failed to parse lock file at: /build/stderred/Cargo.lock29:41
       >29:41
       > Caused by:29:41
       >   lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?29:41
       For full logs, run 'nix log /nix/store/hmfp9y0w181bywzy02b9pyvbd5ai0p6s-stderred-0.1.0-vendor.tar.gz.drv'.
```

What changed
===
* Update stderrred to build with pkgs instead of pkgs-23_05
* Update cargo hash

Test plan
===
```
nix build '.#"python-with-prybar-3.10"'
```
works